### ISSUE TITLE
Screenshot in your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [DocketAlarm/state-court-bulk-docket-pull#17]
Hi there!  I noticed you've got a GUI...

It's uncommon for Python programs to have a GUI, so it's extra special when you run into Python code on GitHub that has a GUI. I think people are more likely to try out a program if they can see how the program looks. Even if they don't try it, it's still nice to be able to see someone's accomplishment.

It would be great to see a screenshot in your readme.md file if you have time to add something. It's really easy with GitHub to embed an image. All you have to do is grab and drop or copy and paste your image into an Issue, just like the one this message is in, and then copy / paste the code that's created by GitHub into you readme.md file. The same code that embeds an image into an Issue can be used to embed the image into the readme.md file.

Thanks for your time and sharing your code on GitHub.

### To add a screenshot to your readme that will show up on your GitHub's "homepage"

* Open an issue in your project
* Copy and paste an image or drag and drop an image file into the issue text area. There are also upload instructions in the issue.
* GitHub will create something that looks like this in your issue:
```
![SNAG-0767](https://user-images.githubusercontent.com/46163555/80380522-b2c09600-886d-11ea-92cc-e88e14e0917c.jpg)
```
* Copy this above line(s) of text that the Issue created for you
* Edit your readme.md file in your project
* Paste the line of text from the Issue in your readme.md
* The image will now be embedded in your readme and will show up when someone visits your GitHub page
* You'll look like a rock star!

No GUI is too small to show people.  If you've taken the time to post it on GitHub, it's worthy of showing everyone.  Trust me here... people LOVE seeing them.  There are not many GUIs in the Python world and you are a part of the movement that's changing that!

**Comment by speedplane** [comment]
Done!
